---
title: GLRT
output: html_notebook
---
### Suppose you wanted to find the GLRT of C={X|n*log(sum|xi|-lambda0*sum|xi| < c)} with significance level alpha = 0.01. Your answer likely includes an expression whose pdf is unknown, and hence it is difficult to algebraically determine a critical value, c, that gives rise to a critical region with a prescribed alpha level. Use a trial-and-error process and simulation to find an approximate c which creates a GLRT with a approx 0.01. Use n = 5 and lambda0 = 2


```{r}
vals <- numeric(100000)
for (i in 1:100000) {
  d = rgamma(1,5,2)
  vals[i] = 5*log(d) - 2*d
}
sorted_values = sort(vals)
c <- sorted_values[100000*0.01]
c
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

